export const FETCH_POSTS = 'FETCH_POSTS';
export const SEARCH_SUBS = 'SEARCH_SUBS';
export const ADD_SUBREDDIT = 'ADD_SUBREDDIT';
export const REMOVE_SUBREDDIT = 'REMOVE_SUBREDDIT';
export const CHANGE_FETCH_STATUS = 'CHANGE_FETCH_STATUS';
