export const ADD_SUBREDDIT = 'ADD_SUBREDDIT';
export const REMOVE_SUBREDDIT = 'REMOVE_SUBREDDIT';


// api actions
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const SEARCH_SUBS_REQUEST = 'SEARCH_SUBS_REQUEST';
export const SEARCH_SUBS_SUCCESS = 'SEARCH_SUBS_SUCCESS';
export const SEARCH_SUBS_FAILURE = 'SEARCH_SUBS_FAILURE';
